package vo

const (
	// DSRequestsSsl ...
	DSRequestsSsl = "requests_ssl"

	// DSRequestsNonSsl ...
	DSRequestsNonSsl = "requests_nonssl"

	// DSRequestsCached ...
	DSRequestsCached = "requests_cached"

	// DSRequestsCachedSsl ...
	DSRequestsCachedSsl = "requests_cached_ssl"

	// DSRequestsCachedNonSsl ...
	DSRequestsCachedNonSsl = "requests_cached_nonssl"

	// DSRequestsUncached ...
	DSRequestsUncached = "requests_uncached"

	// DSRequestsUncachedSsl ...
	DSRequestsUncachedSsl = "requests_uncached_ssl"

	// DSRequestsUncachedNonSsl ...
	DSRequestsUncachedNonSsl = "requests_uncached_nonssl"

	// DSRequestsCachedHits ...
	DSRequestsCachedHits = "requests_cache_hits"

	// DSRequestsCachedHitsSsl ...
	DSRequestsCachedHitsSsl = "requests_cache_hits_ssl"

	// DSRequestsCachedHitsNonSsl ...
	DSRequestsCachedHitsNonSsl = "requests_cache_hits_nonssl"

	// DSBytesNonSsl ...
	DSBytesNonSsl = "bytes_nonssl"

	// DSBytesCached ...
	DSBytesCached = "bytes_cached"

	// DSBytesCachedSsl ...
	DSBytesCachedSsl = "bytes_cached_ssl"

	// DSBytesCachedNonSsl ...
	DSBytesCachedNonSsl = "bytes_cached_nonssl"

	// DSBytesUncached ...
	DSBytesUncached = "bytes_uncached"

	// DSBytesUncachedSsl ...
	DSBytesUncachedSsl = "bytes_uncached_ssl"

	// DSBytesUncachedNonSsl ...
	DSBytesUncachedNonSsl = "bytes_uncached_nonssl"

	// DSBytesCacheHits ...
	DSBytesCacheHits = "bytes_cache_hits"

	// DSBytesCacheHitsSsl ...
	DSBytesCacheHitsSsl = "bytes_cache_hits_ssl"

	// DSBytesCacheHitsNonSsl ...
	DSBytesCacheHitsNonSsl = "bytes_cache_hits_nonssl"

	// DSUpstreamPerformance ...
	DSUpstreamPerformance = "upstream_performance"

	// DSResponseCodes ...
	DSResponseCodes = "response_codes"

	// DSCountryCodes ...
	DSCountryCodes = "country_codes"

	// DSRequestsBlocked ...
	DSRequestsBlocked = "requests_blocked"

	// TypeStats ...
	TypeStats = "stats"

	// TypeHistogram ...
	TypeHistogram = "histogram"

	// RecordTypeA ...
	RecordTypeA = "A"

	// RecordTypeAAAA ...
	RecordTypeAAAA = "AAAA"

	// RecordTypeCNAME ...
	RecordTypeCNAME = "CNAME"

	// RecordTypeMX ...
	RecordTypeMX = "MX"

	// RecordTypeSRV ...
	RecordTypeSRV = "SRV"

	// RecordTypePTR ...
	RecordTypePTR = "PTR"

	// RecordTypeNS ...
	RecordTypeNS = "NS"

	// RecordTypeTXT ...
	RecordTypeTXT = "TXT"
)
